name: Ruff
on: [push, pull_request]
jobs:
  built:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
      - uses: astral-sh/ruff-action@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .

